name: Docker CI/CD

on:
  push:
    branches:
      - "docker"

jobs:
  docker:
    name: Docker Build and Push
    container:
      image: node:20-bookworm
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y docker.io
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kumitterer/matrix-gptbot:latest
      - name: Log in to Forgejo Docker Registry
        uses: docker/login-action@v3
        with:
          registry: git.private.coffee
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to Forgejo Docker Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: git.private.coffee/privatecoffee/matrix-gptbot:latest